config/routes.rb
BusCentral::Application.routes.draw do
  resources :route_stops

  resources :buses
  resources :bus_routes do
    get 'scrap', on: :collection
  end

  mount Resque::Server, :at => "/resque"
  
  root :to => 'bus_routes#index'
end

app/models/bus.rb
class Bus < ActiveRecord::Base
  belongs_to :bus_route
  attr_accessible :bus_number, :description, :last_stop, :latitude, :longitude, :next_stop, :time_to_next_stop
end

app/models/bus_route.rb
BASE_URL = "http://www.coruna.es/guiaLocal/"

class BusRoute < ActiveRecord::Base
  has_many :buses, :class_name => "Bus"
  has_many :route_stops
  
  attr_accessible :first_stop, :last_stop, :route_number, :link
  
  def full_link
    "#{BASE_URL}#{link}"
  end
end

app/models/route_stop.rb
class RouteStop < ActiveRecord::Base
  belongs_to :bus_route
  attr_accessible :distance, :name, :pos, :bus_route
  
  def method_missing(m)
      puts "No method #{m} creating..."
      self.class.send(:define_method, :lol) do
        puts "Method missing magix"
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bus_routes_controller.rb
class BusRoutesController < ApplicationController
  # GET /bus_routes
  # GET /bus_routes.json
  def index
    @bus_routes = BusRoute.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bus_routes }
    end
  end
  
  # GET /bus_routes/scrap 
  def scrap
    Resque.enqueue(CorunaCrawler)
    redirect_to root_path
  end
  
  # GET /bus_routes/1
  # GET /bus_routes/1.json
  def show
    @bus_route = BusRoute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bus_route }
    end
  end

  # GET /bus_routes/new
  # GET /bus_routes/new.json
  def new
    @bus_route = BusRoute.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bus_route }
    end
  end

  # GET /bus_routes/1/edit
  def edit
    @bus_route = BusRoute.find(params[:id])
  end

  # POST /bus_routes
  # POST /bus_routes.json
  def create
    @bus_route = BusRoute.new(params[:bus_route])

    respond_to do |format|
      if @bus_route.save
        format.html { redirect_to @bus_route, notice: 'Bus route was successfully created.' }
        format.json { render json: @bus_route, status: :created, location: @bus_route }
      else
        format.html { render action: "new" }
        format.json { render json: @bus_route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bus_routes/1
  # PUT /bus_routes/1.json
  def update
    @bus_route = BusRoute.find(params[:id])

    respond_to do |format|
      if @bus_route.update_attributes(params[:bus_route])
        format.html { redirect_to @bus_route, notice: 'Bus route was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bus_route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bus_routes/1
  # DELETE /bus_routes/1.json
  def destroy
    @bus_route = BusRoute.find(params[:id])
    @bus_route.destroy

    respond_to do |format|
      format.html { redirect_to bus_routes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  # GET /buses
  # GET /buses.json
  def index
    @buses = Bus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buses }
    end
  end

  # GET /buses/1
  # GET /buses/1.json
  def show
    @bus = Bus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bus }
    end
  end

  # GET /buses/new
  # GET /buses/new.json
  def new
    @bus = Bus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bus }
    end
  end

  # GET /buses/1/edit
  def edit
    @bus = Bus.find(params[:id])
  end

  # POST /buses
  # POST /buses.json
  def create
    @bus = Bus.new(params[:bus])

    respond_to do |format|
      if @bus.save
        format.html { redirect_to @bus, notice: 'Bus was successfully created.' }
        format.json { render json: @bus, status: :created, location: @bus }
      else
        format.html { render action: "new" }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buses/1
  # PUT /buses/1.json
  def update
    @bus = Bus.find(params[:id])

    respond_to do |format|
      if @bus.update_attributes(params[:bus])
        format.html { redirect_to @bus, notice: 'Bus was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1
  # DELETE /buses/1.json
  def destroy
    @bus = Bus.find(params[:id])
    @bus.destroy

    respond_to do |format|
      format.html { redirect_to buses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/route_stops_controller.rb
class RouteStopsController < ApplicationController
  # GET /route_stops
  # GET /route_stops.json
  def index
    @route_stops = RouteStop.all order: "pos asc"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @route_stops }
    end
  end

  # GET /route_stops/1
  # GET /route_stops/1.json
  def show
    @route_stop = RouteStop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @route_stop }
    end
  end

  # GET /route_stops/new
  # GET /route_stops/new.json
  def new
    @route_stop = RouteStop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @route_stop }
    end
  end

  # GET /route_stops/1/edit
  def edit
    @route_stop = RouteStop.find(params[:id])
  end

  # POST /route_stops
  # POST /route_stops.json
  def create
    @route_stop = RouteStop.new(params[:route_stop])

    respond_to do |format|
      if @route_stop.save
        format.html { redirect_to @route_stop, notice: 'Route stop was successfully created.' }
        format.json { render json: @route_stop, status: :created, location: @route_stop }
      else
        format.html { render action: "new" }
        format.json { render json: @route_stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /route_stops/1
  # PUT /route_stops/1.json
  def update
    @route_stop = RouteStop.find(params[:id])

    respond_to do |format|
      if @route_stop.update_attributes(params[:route_stop])
        format.html { redirect_to @route_stop, notice: 'Route stop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @route_stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /route_stops/1
  # DELETE /route_stops/1.json
  def destroy
    @route_stop = RouteStop.find(params[:id])
    @route_stop.destroy

    respond_to do |format|
      format.html { redirect_to route_stops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bus_routes_helper.rb
module BusRoutesHelper
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/helpers/route_stops_helper.rb
module RouteStopsHelper
end

app/views/bus_routes/_form.html.erb
<%= form_for @bus_route, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :route_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :route_number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :first_stop, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_stop, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_stop, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_stop, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :link, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bus_routes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bus_routes/edit.html.erb
<%- model_class = BusRoute -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bus_routes/index.html.erb
<%- model_class = BusRoute -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:route_number) %></th>
      <th><%= model_class.human_attribute_name(:first_stop) %></th>
      <th><%= model_class.human_attribute_name(:last_stop) %></th>
      <th><%= model_class.human_attribute_name(:link) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bus_routes.each do |bus_route| %>
      <tr>
        <td><%= link_to bus_route.id, bus_route_path(bus_route) %></td>
        <td><%= bus_route.route_number %></td>
        <td><%= bus_route.first_stop %></td>
        <td><%= bus_route.last_stop %></td>
        <td><%= link_to "Ver link", bus_route.full_link, title: bus_route.full_link, target: :blank %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bus_route_path(bus_route), :class => 'btn btn-mini' %>
                      
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bus_route_path(bus_route),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bus_route_path,
            :class => 'btn btn-primary' %>

app/views/bus_routes/new.html.erb
<%- model_class = BusRoute -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bus_routes/show.html.erb
<%- model_class = BusRoute -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:route_number) %>:</strong></dt>
  <dd><%= @bus_route.route_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:first_stop) %>:</strong></dt>
  <dd><%= @bus_route.first_stop %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_stop) %>:</strong></dt>
  <dd><%= @bus_route.last_stop %></dd>
  <dt><strong><%= model_class.human_attribute_name(:link) %>:</strong></dt>
  <dd><%= @bus_route.link %></dd>
  <dt><strong>Paradas: </strong></dt>
  <dd>
    <% if !@bus_route.route_stops.blank? %>
      <ul>
      <% for stop in @bus_route.route_stops.all(order: "pos asc") %>
        <li><%= "#{stop.pos} - #{stop.name} (#{stop.distance}m)"%></li>
      <% end %>
      </ul>
    <% else %>
      No hay paradas asignadas a esta ruta
    <% end %>
    
  </dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bus_routes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bus_route_path(@bus_route), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bus_route_path(@bus_route),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/buses/_form.html.erb
<%= form_for @bus, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :bus_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :bus_number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_stop, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_stop, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :next_stop, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :next_stop, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :time_to_next_stop, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :time_to_next_stop, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :latitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :latitude, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :longitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :longitude, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :bus_route_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :bus_route_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                buses_path, :class => 'btn' %>
  </div>
<% end %>

app/views/buses/edit.html.erb
<%- model_class = Bu -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/buses/index.html.erb
<%- model_class = Bus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:bus_number) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:last_stop) %></th>
      <th><%= model_class.human_attribute_name(:next_stop) %></th>
      <th><%= model_class.human_attribute_name(:time_to_next_stop) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:bus_route_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @buses.each do |bus| %>
      <tr>
        <td><%= link_to bus.id, bus_path(bus) %></td>
        <td><%= bus.bus_number %></td>
        <td><%= bus.description %></td>
        <td><%= bus.last_stop %></td>
        <td><%= bus.next_stop %></td>
        <td><%= bus.time_to_next_stop %></td>
        <td><%= bus.latitude %></td>
        <td><%= bus.longitude %></td>
        <td><%= bus.bus_route_id %></td>
        <td><%=l bus.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bus_path(bus), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bus_path(bus),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bus_path,
            :class => 'btn btn-primary' %>

app/views/buses/new.html.erb
<%- model_class = Bu -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/buses/show.html.erb
<%- model_class = Bu -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:bus_number) %>:</strong></dt>
  <dd><%= @bus.bus_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @bus.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_stop) %>:</strong></dt>
  <dd><%= @bus.last_stop %></dd>
  <dt><strong><%= model_class.human_attribute_name(:next_stop) %>:</strong></dt>
  <dd><%= @bus.next_stop %></dd>
  <dt><strong><%= model_class.human_attribute_name(:time_to_next_stop) %>:</strong></dt>
  <dd><%= @bus.time_to_next_stop %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @bus.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @bus.longitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bus_route_id) %>:</strong></dt>
  <dd><%= @bus.bus_route_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              buses_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bus_path(@bus), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bus_path(@bus),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BusCentral" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">BusCentral</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Rutas", bus_routes_path  %></li>
              <li><%= link_to "Buses", buses_path  %></li>
              <li><%= link_to "Paradas", route_stops_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">BusCentral</li>
              <li><%= link_to "Recargar", scrap_bus_routes_path, class: "btn"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Softwhisper SL 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/route_stops/_form.html.erb
<%= form_for @route_stop, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :position, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :position, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :distance, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :distance, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :bus_route_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :bus_route_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                route_stops_path, :class => 'btn' %>
  </div>
<% end %>

app/views/route_stops/edit.html.erb
<%- model_class = RouteStop -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/route_stops/index.html.erb
<%- model_class = RouteStop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:pos) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:distance) %></th>
      <th><%= model_class.human_attribute_name(:bus_route_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @route_stops.each do |route_stop| %>
      <tr>
        <td><%= link_to route_stop.id, route_stop_path(route_stop) %></td>
        <td><%= route_stop.pos %></td>
        <td><%= route_stop.name %></td>
        <td><%= route_stop.distance %> m</td>
        <td><%= route_stop.bus_route.route_number if route_stop.bus_route %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_route_stop_path(route_stop), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      route_stop_path(route_stop),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_route_stop_path,
            :class => 'btn btn-primary' %>

app/views/route_stops/new.html.erb
<%- model_class = RouteStop -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/route_stops/show.html.erb
<%- model_class = RouteStop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:pos) %>:</strong></dt>
  <dd><%= @route_stop.position %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @route_stop.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:distance) %>:</strong></dt>
  <dd><%= @route_stop.distance %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bus_route_id) %>:</strong></dt>
  <dd><%= @route_stop.bus_route_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              route_stops_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_route_stop_path(@route_stop), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              route_stop_path(@route_stop),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>